### PR TITLE
Fixed: Text selection color should match design

### LINKED ISSUE #1611: Text selection color should match design
Right now, in most places, text selection is rendered with a dark blue
Screenshot 2021-01-11 at 17 27 53

Check figma and adjust accordingly

### PR DESCRIPTION
**Pull request by staked-smart-ace**
Fixes #1611

### CODE REVIEW

**Comment by PascalPrecht** [comment]
I think we have many more places where text can be selected. Those places need to be addresses as well. 
For example the chat input, chat messages etc.

If we can't nail them all in this first PR, that's fine but we should try at least :D

Oh and regarding your commit message, that one is probably on me, see here: https://github.com/status-im/nim-status-client/pull/1659/commits/fcbf1ddc5a03fff9ca5468f2e20cf28b18ccf845
it would be wonderful if you commit would say what it does, otherwise it's hard to work with it later on. So putting the title of this PR in there would already help a lot.

Notice that you can have multi-line commit messages.

**Review by jrainville — COMMENTED** [review]
Nice start.

Like Pascal said, there are probably a lot more places where we want to change the color. It's already great that you identified the `StyledTextField`.

Other files that would need this change are:
- `StyledtextEdit`
- `StyledTArea`
- `StyledTextArea`

**Comment by staked-smart-ace** [comment]
> I think we have many more places where text can be selected. Those places need to be addresses as well.
> For example the chat input, chat messages etc.

Basically, almost of the input box, search box is based on StyledTextField.
And then, chat input box is applied selection color.
And then, also chat message is applied it by applying to StyledTextEdit.

**Comment by jrainville** [comment]
Cool, you're just missing those two now:
StyledTArea
StyledTextArea

**Comment by staked-smart-ace** [comment]
ok, I just updated also TArea/TextArea

**Review by jrainville — APPROVED** [review]
Perfect!

**Pull request merged**
