### PR TITLE
Add support for local contact nickname

### LINKED ISSUE #833: add local contact names
see

https://discuss.status.im/t/add-local-contact-names/1789
https://github.com/status-im/status-react/pull/11106
https://github.com/status-im/status-react/issues/11046
https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=4067%3A2905

### PR DESCRIPTION
**Pull request by jrainville**
Fixes #833 

Adds a nickname popup to set the nickname of a contact. It is then saved in the Contact itslef in Sttaus-Go.

I also refactored quickly chatModel because it had `addContact`, `blockContact`, etc. and profileModel had it too. So I made the decision to only keep the profileModel ones.

image

image

image

### CODE REVIEW

**Comment by richard-ramos** [comment]
Shouldnt the title "Nickname" be replaced by that user's three word nickname?

**Comment by richard-ramos** [comment]
Screenshot from 2020-09-17 13-24-04
The "ENS Username" value is being replaced by the local nickname

**Comment by richard-ramos** [comment]
These places are not displaying the local name

New group modal
Screenshot from 2020-09-17 13-25-18

Group status message
Screenshot from 2020-09-17 13-25-43

Group info
Screenshot from 2020-09-17 13-26-04

**Review by richard-ramos — CHANGES_REQUESTED** [review]
Good work, dude!
I left some comments on places where local contact nicknames arent being shown

**Comment by jrainville** [comment]
> Shouldnt the title "Nickname" be replaced by that user's three word nickname? (and also include the identicon)?

I copied the Mobile design, since we don't have a desktop design.  I don't mind changing it, but we coudl wait for @simonricoo to make a design too.

> The "ENS Username" value is being replaced by the local nickname

Ah, that's not intended. I know what the problem is 

> These places are not displaying the local name

If you're talking about the ENS name, it should have precedence on local name I think? I'm not sure

**Comment by richard-ramos** [comment]
> If you're talking about the ENS name, it should have precedence on local name I think? I'm not sure

cc: @simonricoo  for his thoughts

**Comment by jrainville** [comment]
@richard-ramos I fixed the problem with group chats and the overriding of ENS

I'm gonna rebase now

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
