### PR TITLE
feat: make channel list compact in compact mode

### PR DESCRIPTION
**Pull request by jrainville**
Branched on top of https://github.com/status-im/nim-status-client/pull/567

image

### CODE REVIEW

**Comment by richard-ramos** [comment]
Removing the identicon would make the channel list even smaller!

**Comment by jrainville** [comment]
https://i.ytimg.com/vi/IGXYzNm29bQ/hqdefault.jpg

The text is about the same size as the identicon, so it wouldn't really make a difference

**Comment by richard-ramos** [comment]
Maybe? here's is how it looks after doing some sick photoshop: 
image

**Comment by richard-ramos** [comment]
I think we could even remove the last message time :dagger: !

**Comment by jrainville** [comment]
Aaah, so you're just concerned about the width. I mean, you can already reduce the width yourself using the border in the middle. =
An added thing we could do is an `if` where if the width is smaller than X, hide the date and/or identicon

**Comment by emizzle** [comment]
I tested the branch and it looks good, well done! I agree with @richard-ramos, if the identicons were removed, it would allow the channel list width to be reduced quite a lot more.

**Comment by jrainville** [comment]
I'll just wait until we have a design haha. Anyway, doing the changes you guys proposed is very easy from there

**Pull request merged**
