### PR TITLE
feat: allow users to restore notification settings

### LINKED ISSUE #1280: Muted Chats, Muted Users, Reset Notification Settings not working
On the click nothing happens... 
Screenshot_2020-11-03_at_15_50_33

### PR DESCRIPTION
**Pull request by PascalPrecht**
Fixes #1280

### CODE REVIEW

**Comment by PascalPrecht** [comment]
This works except for the general `notificationSetting` (the first three radio buttons in the settings view).

I assume that's related to the binding loop I'm seeing. Maybe someone can take a look? Couldn't figure out why it's not working for just that button group. Notice that there are more radio buttons with settings and there, restoring defaults works just fine...

**Review by jrainville — COMMENTED** [review]
Looks good. I'll take a look at your binding loop

**Comment by jrainville** [comment]
@PascalPrecht I added a commit that fixes your issue.
The problem was that the `checked` property was binded to the appSetting, which is ok, but then, changing appSetting from an external source caused `checked` to change, proc'ing `onCheckedChanged`, which in turn changed `checked` again, hence the binding loop.

**Comment by PascalPrecht** [comment]
Landed as https://github.com/status-im/nim-status-client/commit/ede6afff260f90eddb6f2683db421b5e664a26be

**Pull request closed without merging**
