### PR TITLE
Updated profile popup modal to show existing nickname of the current user

### PR DESCRIPTION
**Pull request by staked-smart-ace**
Fixed: #1604

### CODE REVIEW

**Review by PascalPrecht — APPROVED** [review]
Well done bud

**Comment by staked-smart-ace** [comment]
I just updated commit messages in order to include original issue number

**Comment by PascalPrecht** [comment]
Hey man!
Don't wanna be picky here :D
But what you did was updating the PR title. Your commit is unchanged. To change your commit message you'd need to do something like

```
$ git commit --amend
# change your commit message
$ git push -f origin your_branch_name
```

**Review by jrainville — APPROVED** [review]

**Comment by jrainville** [comment]
I'm gonna be honest, I don't personally put `Fixes #x" in my commit messages because.. I keep forgetting. So don't beat yourself up if you don't.

Usually, just putting "Fixes #x"  in the PR message links the issue correctly already.

**Pull request merged**
