### PR TITLE
feat: currency list translations

### PR DESCRIPTION
**Pull request by hydr063n**
Fixes: https://github.com/status-im/nim-status-client/issues/846

I've added the translations for currencies in these 3 files (where I found US Dollar and Euro):

```
qml_en.ts
qml_la.ts
qml_bel.ts
```

I updated the Currencies files to have the correct text-ids in the comments and qsTrId section of the `Currencies.qml` file. Then compiled the translations to .qm files with `lrelease -idbased nim-status-client.pro`

### CODE REVIEW

**Review by PascalPrecht — CHANGES_REQUESTED** [review]
LGTM!

@jrainville should have another look

Only thing I'd ask for is squashing those commits into a single one and ideally use proper commit message conventions! :)

**Review by jrainville — COMMENTED** [review]
Nice work @hydr063n that looked tedious.

BTW, you don't have to add stuff manually to the `.ts` files unless you're actually looking to translate.
QT does it all by itself.

Just run `lupdate nim-status-client.pro` in the `ui` directory and it will update all the remaining `.ts` files.

Then you can re-run `lrelease -idbased i18n/*.ts`, in the same directory, to generate the other binary files.

For more details on how our translation workflow looks like, you can check this out: https://github.com/status-im/nim-status-client/blob/master/scripts/translationScripts/README.md
(you don't have to run the Node scripts in your case)

**Comment by hydr063n** [comment]
hey @PascalPrecht thanks for review, i added a new commit which includes all the work in one commit. ill write better commit messages in future

@jrainville thanks for the tips after reading your tutorial i figured out that the `app/AppLayouts/Wallet/data/Currencies.qml` wasn't in the project file `nim-status-client.pro` and that's why the ids and sources weren't getting picked up by `lupdate` . My mistake was then deciding to manually add the messages. This time around I added the currencies file and `lupdate` runs smoothly without any manual work. Thanks for the tips!!

**Review by jrainville — APPROVED** [review]
Great job! Thanks a lot

**Pull request merged**
