### PR TITLE
feat: improve style of the notification box

### PR DESCRIPTION
**Pull request by jrainville**
Use the Channel box for that

image

### CODE REVIEW

**Comment by jrainville** [comment]
Interesting, that's the drop shadow. It's weird that it behaves like this on Mac

**Comment by richard-ramos** [comment]
Isn't it possible it's because a new notification is being created for each message received, and all the drop shadows opacities are beign added?

**Comment by jrainville** [comment]
Hmm, maybe. I thought Iuri fixed that issue, but we seem to have a `createObject` on each new notification.

@michaelsbradleyjr do you have that black atrocity all the time, or just when you log in and there is possibly multiple notifications overlapping?

**Comment by michaelsbradleyjr** [comment]
@jrainville I had it when I used my iPhone to reply to the user of my dev build in `#test`, so it was just one notification.

**Pull request merged**
