### PR TITLE
refactor(chat): make activeChannel a ChatItem to expose relevant info…

### PR DESCRIPTION
**Pull request by PascalPrecht**
…rmation to the view

Tons of kudos to @emizzle for helping me getting this sorted.
Also, this is based on #248

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Screenshot 2020-06-02 at 17 14 15

**Comment by iurimatias** [comment]
@PascalPrecht https://github.com/status-im/nim-status-client/blob/master/src/app/chat/views/channels_list.nim already contains the chatItem, can't this be simplified to be get the chatItem from there instead?

**Comment by PascalPrecht** [comment]
@iurimatias that's exactly what we do here: https://github.com/status-im/nim-status-client/pull/250/files#diff-ed6f2995c8c8aa27163e93371ed67be4R61

Still need to wrap it in a QObject so we can derive a QVariant to access its properties inside QML, which is what essentially this PR is doing.

Lemme know if you think this can/should be done in a different way.

**Comment by iurimatias** [comment]
@PascalPrecht I found in the past that objects that in a `QAbstractListModel` don't need to have the whole QVariant business for each property. so basically wondering if we can get rid of `views/chat_item.nim` completely, and make `activeChannel` a ChatItem (exposed as a QVariant), we could pair up tomorrow to try it out if you want

**Comment by PascalPrecht** [comment]
> and make activeChannel a ChatItem (exposed as a QVariant)
That's what I initially tried. Thing is that a `QtProperty` has to be of any primitive type (`string`, `int` etc) **or** a `QVariant`. 

Exposing the `ChatItem` directly won't work without it. Happy to take a look again tomorrow though!

**Comment by iurimatias** [comment]
@PascalPrecht for reference: https://github.com/status-im/nim-status-client/pull/101/files

**Comment by PascalPrecht** [comment]
@iurimatias just to follow up on your latest comments here:

Exposing `activeChannel` as a `ChatItem` won't work without making it a `QtPropery[QVariant]`. For this to be a `QVariant` it has to be a `QObject`, there doesn't seem to be a way around that. I just gave it a spin with regards to your comment and it won't compile like that. If we remove the QtProperty altogether, the `activeChannel` won't be available inside QML.

Notice also that we're talking about a single property that accessed from the view and it doesn't live inside an `QAbstractListModel`. While your approach works in the channel list, it doesn't work for the activeChannel.

**Pull request merged**
