### PR TITLE
fix: add missing popup

### PR DESCRIPTION
**Pull request by hydr063n**

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Is this Dialog used anywhere? Or this PR is just in preparation for another one?

**Comment by hydr063n** [comment]
Yes, this Dialog is missing from PR #1442 that's already merged. I made a mistake by committing changes with `-am` flag and thus the untracked Dialog didn't get included in the commit

**Review by jrainville — APPROVED** [review]
Yes I just saw. It's all good.
Pascal already pushed a commit to patch the fact that master was broken, so if you want you can remove that patch as part of this PR https://github.com/status-im/nim-status-client/pull/1480

**Comment by hydr063n** [comment]
Done!

**Review by jrainville — APPROVED** [review]
Perfect

**Pull request merged**
