### PR TITLE
sqlcipher

### PR DESCRIPTION
**Pull request by iurimatias**

### CODE REVIEW

**Comment by iurimatias** [comment]
@emizzle @PascalPrecht could you please test this branch on your mac plz (it works for me, but we should test in other machines as well)

**Comment by emizzle** [comment]
it failed for me:
```shell
checking build system type... x86_64-apple-darwin19.4.0
checking host system type... x86_64-apple-darwin19.4.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/emizzle/repos/github.com/status-im/nim-status-client/vendor/sqlcipher':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [vendor/sqlcipher/sqlite3.c] Error 77
```
further error info (from config.log):
```shell
configure:2860: checking whether the C compiler works
configure:2882: gcc -DSQLITE_HAS_CODEC  -lcrypto conftest.c  >&5
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:2886: $? = 1
configure:2924: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "sqlcipher"
| #define PACKAGE_TARNAME "sqlcipher"
| #define PACKAGE_VERSION "3.31.0"
| #define PACKAGE_STRING "sqlcipher 3.31.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2929: error: in `/Users/emizzle/repos/github.com/status-im/nim-status-client/vendor/sqlcipher':
configure:2931: error: C compiler cannot create executables
```

**Comment by emizzle** [comment]
FWIW, have tried changing the build flags to:

```
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_ENABLE_FTS3" LDFLAGS="-lcrypto" && \
./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_FTS3" LDFLAGS="-lcrypto" && \
```
and neither seemed to work

**Comment by stefantalpalaru** [comment]
What's the output of `ls -l /usr/lib/libcrypto.*`?

It would appear that with macOS Catalina, Apple found a new way to punish developers - if you link to "libfoo.dylib", you get a broken stub, to force you to link "libfoo.0.1.2.dylib" instead: https://github.com/saltstack/salt/pull/56958

**Comment by PascalPrecht** [comment]
Same issue for me:

```
[ 36%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQMetaObject.cpp.o
[ 45%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQDeclarative.cpp.o
[ 54%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQObject.cpp.o
[ 63%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DOtherSideTypesCpp.cpp.o
[ 72%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQObjectImpl.cpp.o
[ 81%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQAbstractItemModel.cpp.o
[ 90%] Building CXX object lib/CMakeFiles/DOtherSide.dir/src/DosQQuickImageProvider.cpp.o
[100%] Linking CXX shared library libDOtherSide.dylib
[100%] Built target DOtherSide
echo -e "\\e[92mBuilding:\\e[39m" "sqlcipher"
\e[92mBuilding:\e[39m sqlcipher
cd vendor/sqlcipher && \
          ./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" && \
                /Applications/Xcode.app/Contents/Developer/usr/bin/make sqlite3.c
checking build system type... x86_64-apple-darwin19.3.0
checking host system type... x86_64-apple-darwin19.3.0
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/pascalprecht/projects/status-im/nim-status-client/vendor/sqlcipher':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [vendor/sqlcipher/sqlite3.c] Error 77
```

**Comment by stefantalpalaru** [comment]
> -rwxr-xr-x  1 root  wheel    32992 Jan 23 13:58 /usr/lib/libcrypto.dylib

Yeah, this is obviously too small to be a real library. It used to be a symlink, back when they were still pretending to be a POSIX system.

Issue confirmed here - https://forums.developer.apple.com/message/388348 :

```text
Application Specific Information:  
/usr/lib/libcrypto.dylib  
abort() called  
Invalid dylib load. Clients should not load the unversioned libcrypto dylib as it does not have a stable ABI.
```

Now how do we detect and link something like "libcrypto.0.9.8.dylib"? Would "-lcrypto.0.9.8" work?

**Comment by richard-ramos** [comment]
After some research, it seems that we will not need to use SQLCipher, due to status-go already implementing functions for storing the chats, contacts, settings, etc. 
We might have to revise this task again in the future once we work on the integration with nimbus

**Pull request closed without merging**
