### PR TITLE
Update nickname modal to confirm when press Enter key

### PR DESCRIPTION
**Pull request by staked-smart-ace**
Fixes: #1605

### CODE REVIEW

**Comment by PascalPrecht** [comment]
Changes LGTM. Also tested this locally - great job! 💪

**Comment by PascalPrecht** [comment]
One tiny comment: the `Fixes: #1605` line needs to be in the commit message (it will then show up automatically in the PR text body). If it's only in the PR body but not actually the commit, it's kinda "gone" once the PR is merged and GitHub won't recognize it as a commit that fixes the particular issue.

So if you want bonus points, update your commit with that line :)

**Review by PascalPrecht — APPROVED** [review]

**Comment by staked-smart-ace** [comment]
Ok, I just updated the commit message also.

**Comment by PascalPrecht** [comment]
Same as: https://github.com/status-im/nim-status-client/pull/1648#issuecomment-759488127

**Review by jrainville — APPROVED** [review]

**Comment by staked-smart-ace** [comment]
Sorry for late reply.
You already approved this PR. May I commit again at this moment?

**Comment by PascalPrecht** [comment]
This has landed as https://github.com/status-im/nim-status-client/commit/9facb148085fc2b9f958c7f870027971339f47a0
@staked-smart-ace notice that I put the actually message back into the commit

**Pull request closed without merging**
