### PR TITLE
Fixes: Emoji messages are rendered too big

### LINKED ISSUE #1610: Emoji messages are rendered too big
When sending a single emoji message they are rendere quite huge
Screenshot 2021-01-11 at 17 24 48
Screenshot 2021-01-11 at 17 25 02

Emoji mixed with text on the other hand do not
Screenshot 2021-01-11 at 17 25 15

### PR DESCRIPTION
**Pull request by staked-smart-ace**
Fixes #1610

### CODE REVIEW

**Review by jrainville — APPROVED** [review]

**Comment by richard-ramos** [comment]
Woudlnt this make the emoji messages show the same size as when they're part of a text message? I'm wondering if it wouldnt be better to change the size of the emoji images instead from 72x72 to a smaller value greater than 20x20?

**Comment by staked-smart-ace** [comment]
I just followed Figma design.
Who could make the final decision for this issue?

**Comment by staked-smart-ace** [comment]
And then, do you know why the windows build has been failed?

**Comment by richard-ramos** [comment]
> I just followed Figma design.
> Who could make the final decision for this issue?

fair enough. I see the sizing for emojis is not clear in Figma. cc: @simonricoo for feedback.

> And then, do you know why the windows build has been failed?

Just restarted the Windows build to see if the issue persists

**Comment by staked-smart-ace** [comment]
Ok, let me update Emoji size as @simonricoo mentioned.

**Review by jrainville — APPROVED** [review]

**Pull request merged**
